services:
  notebook:
    build:
      context: .
    command: uv run jupyter notebook --notebook-dir=/notebooks --ip 0.0.0.0 --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''
    volumes:
      - ./notebooks:/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]    
    ports:
      - 8888:8888