services:
  magenta-worker:
    container_name: magenta-worker
    build:
      context: .
    command: jupyter notebook --notebook-dir=/notebooks --ip 0.0.0.0 --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''
    volumes:
      - ./notebooks:/notebooks
      - ./cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]    
    ports:
      - 8888:8888
    env_file:
      - .env
