
services:
  worker-rm:
    container_name: worker-rm
    build:
      context: .
      dockerfile: mesh.Dockerfile
    command: rq worker --url redis://192.168.1.18:6379 queuerm 
    env_file:
      - .env
    volumes:
      - model_cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  model_cache:
    name: model_cache

