[project]
name = "remote-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonathan Scheer", email = "jonatron@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "flash-attention>=1.0.0",
    "polars>=1.31.0",
    "xformers>=0.0.31.post1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "notebook>=7.4.4",
    "pytest>=8.4.1",
    "ruff>=0.12.3",
]


